# Generated by Django 5.0.6 on 2024-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
