# Generated by Django 5.0.6 on 2024-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0002_blogpost_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
