# Generated by Django 5.0.6 on 2024-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0003_blogpost_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image_caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="blog_api.tag"
            ),
        ),
    ]
