# Generated by Django 5.0.6 on 2024-06-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0005_screenshot_techtag_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="screenshots",
            field=models.ManyToManyField(
                blank=True, related_name="project_images", to="blog_api.screenshot"
            ),
        ),
    ]
