# Generated by Django 5.0.6 on 2024-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0006_alter_project_screenshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
